const eduList2 = [
    
    {
      id:21,
      title: "Digital-Marketing",
     what:"Digital marketing is the act of promoting products and services through digital channels, such as social media, SEO, email, and mobile apps. Any form of marketing that involves electronic devices is considered digital marketing.  It can be done online and offline; in fact, both kinds are important for a well-rounded digital marketing strategy.",
     img:"https://neilpatel.com/wp-content/uploads/2021/07/digital-marketing_featured-image.png",
     vid:"https://www.youtube.com/watch?v=RNh8VHc8qkk",
     course:"Udemy,Upgrad,Simlilearn,Coursera,Intellipat",
     ben:"Benefits of digital marketing include the following:1.Global and local reach. Individuals can see the same ad in different time zones or across the globe. Digital marketing also improves local ad visibility, so organizations can customize their locally targeted ads.2.Targeting specific audiences. Customers and prospective customers can stay connected to brands through email or social media platforms, where organizations can then communicate with them or test offers to gain insights.3.Cost-effectiveness. Digital marketing is less expensive than traditional forms of marketing, such as TV spots. It costs almost nothing to promote through email campaigns and social media.4.Customized channels. Digital marketing channels can be marketed differently, depending on the organization and the platform it's on. Marketing teams within an organization can find their best and strongest forms of marketing and modify those methods as needed.",
     type:"SEO,SEM,SMM,PPC,CONTENT MARKETING,EMAIL-MARKETING,AFFILIATE-MARKETING",
     imp:"Digital marketing helps an organization appeal to a much larger audience than it could through traditional marketing methods because the reach of the internet is worldwide. This marketing method also enables organizations to target prospective customers who are most likely to buy their product or service. For example, a company can advertise holiday sales by emailing past customers or by sharing news of the deals on social media. Organizations have a number of different online methods they can use to reach out to customers, including through emails, social media, text, banner advertisements or affiliates.Social media provides a common way for individuals to interact and communicate with organizations. Likewise, marketers can collect insights from their target audience on these platforms and increase customer engagement by communicating with them. Digital marketing strategies can be quickly shifted as needed. The platform and format of communication can be changed if the target audience moves platforms, for example."
    },
    {
        id: 22,
        title: "Web-Development",
        course:"Udemy,Coding-Ningas,Simlilearn,Coursera,Masai-School",
       what:"Web development refers in general to the tasks associated with developing websites for hosting via intranet or internet. The web development process includes web design, web content development, client-side/server-side scripting and network security configuration, among other tasks.",
       img:"https://www.skypotential.com/wp-content/uploads/2021/04/beneits-of-web-development.jpg",
       vid:"https://www.youtube.com/watch?v=MkcfB7S4fq0",
       ben:"For computer programming, web development is an umbrella term that defines the profession and responsibilities of a developer in creating a website. It is an excellent option for students to make their brilliant career in software industry. To become an expert developer, one should have a bachelor’s degree in computer science. You should work as a trainee in any software agency to grasp a solid hands-on practice and sharpen your technical skills in coding.The median annual salary for web developers in the US is $78,300, according to the Bureau of Labor Statistics (BLS) [1]. However, web developers in the US can earn up to $249,297 according to Glassdoor salary insights [2]. How much you earn will depend on many factors, including where you work, what industry you work in, and how much experience you have. BLS estimates 23 percent industry growth for web developers between 2021-2031, a faster-than-average rate compared to other occupations. One of the driving forces behind this increase in web development jobs is the growth of e-commerce. Companies are becoming more reliant on functioning websites that operate on multiple devices to do business.",
       type:"Frontend-Developer,Backend-Developer,Fullstack-Developer",
       imp:"As a web developer, you could work for a company or agency, or as a freelancer taking on projects for individual clients. Your tasks will vary depending on your work situation, but day-to-day responsibilities might generally include:Designing user interfaces and navigation menusWriting and reviewing code for sites, typically HTML, XML, or JavaScriptIntegrating multimedia content onto a siteTesting web applications,Troubleshooting problems with performance or user experience"
      },
    {
        id: 23,
        title: "Data-Science",
        course:"Upgrad,Newton-School,Simplilearn,Intellipat,Greatlearning",
        what:"Data Science is a field of study that deals with the collection, analysis, and processing various data or information to extract solutions. It deals with the understanding of many structured and unstructured data with specialised knowledge to get the required insights. Only professionals having specialised knowledge in the field of Data Science can carry out these activities. ",
       img:"https://thumbs.dreamstime.com/b/big-data-science-analysis-business-technology-concept-virtual-screen-big-data-science-analysis-business-technology-concept-145015243.jpg",
       vid:"https://www.youtube.com/watch?v=jtn-hRJjl68",
       ben:"Subjects such as Analytics and Data Science have emerged as the biggest needs of every company all over the world. For every activity that a business performs should be later analysed by data science professionals to extract valuable information. Companies from every sector such as Finance, Marketing, Banking, and IT require professionals to manage, analyse, and give valuable solutions for their company. A data scientist is one of the most important and in-demand jobs in the field of data science.With the salary structure and the increased demand, the job of a data scientist has been declared as one of the trendiest jobs of the 21st century, according to IBM. With the growth of the economy of India and the growth of the business sector, data science has a great scope in India.There is also a huge demand for professions specialised in the field of data science all over the world. Anyone from any background can make a career as a data scientist, and therefore, it is one of the best options for students willing to make a career in this field. ",
       type:"1. Machine Learning Experts,2. Actuarial Scientist,3. Mathematician,4. Business Analyst,5. Data Warehousing Expert,6. Data Engineer,7. Data Mining Expert",
       imp:"In order to pursue a career in data science, having a degree in any of the following disciples, i.e., mathematics, linear algebra, statistics, computer science, or information technology, is preferred. Statistics, Programming, and mathematics together form the heart of data science; hence having a strong foundation in these areas is extremely necessary. If someone does not have an academic degree in the above-mentioned areas, they can take up some type of data science courses and establish themselves in this field. From the beginning itself, it is difficult to figure out a role that fulfills our interests or utilizes our complete potential. Hence, exploring different areas in artificial intelligence and doing different types of data science projects would help in finding the best fit for oneself. Learning Python or R programming language can help aspirants in getting an edge over their competitors. Software programming skills benefit in performing data-related activities smoothly, much more quickly, and efficiently as compared to manual intervention. Data is stored and managed in databases, queries are applied, and the resultant outcome helps in making a decision further. Thus, knowing about any databases like SQL can ease a lot many problems; it gets added as a feather in a hat full of skillset.  Check out KnowledgeHut’s best Data Science certification, It has an elaborative curriculum on the constitutional idea of data science, and it provides a lot of clarity to data science practitioners."
      },
   
    
    {
        id: 25,
      title: "JEE",
      course:"Akash-Institute,Ellen,Career-Launcher,Unacademy,Byju's",
      what:"The Joint Entrance Examination (JEE) is an engineering entrance assessment conducted for admission to various engineering colleges in India. It is constituted by two different examinations: the JEE-Main and the JEE-Advanced.The Joint Seat Allocation Authority (JoSAA) conducts the joint admission process for a total of 23 Indian Institutes of Technology, 31 National Institutes of Technology, 25 Indian Institutes of Information Technology campuses and other Government Funded Technical Institutes (GFTIs) based on the rank obtained by a student in JEE-Main or JEE-Advanced, depending on the engineering college.[1]",
     img:"https://akm-img-a-in.tosshub.com/indiatoday/images/story/202008/learn-1996846_1280.jpeg?size=690:388",
     vid:"https://www.youtube.com/watch?v=lmiMyMQrlSI",
     ben:"Buy the required books and study material for JEE:Collect all the required books and material for JEE preparation. Try to follow a JEE study material so that you can focus on JEE syllabus topics only. Don’t undermine the NCERTs. Solved examples and summaries in NCERT textbooks are very helpful for JEE.Create a study schedule and follow it every day:Follow a study routine, a JEE timetable, giving equal importance to Math, Physics and Chemistry. Consistency is very important in JEE preparation. Instead of studying all night one day and sleeping on the next day, it is better to study for equal hours on both days.Eliminate all distractions at home:Staying all the time at home may lead to frustrations and boredom, so it’s crucial that you don’t get distracted from your studies and preparation. Avoid spending excessive time on social media be it Facebook, WhatsApp, Twitter or Instagram. Get rid of all such unproductive things from your life for the sake of getting into an IIT or NIT.Start loving Physics, Chemistry and Math:Try to make studies fun and interesting through smart approaches, real life examples and with the help of persuasive teachers. Start enjoying your studies and you are on track to crack JEE.Manage your time well between studies and other tasks",
     type:"Main Exam,Advance Exam As mentioned above admissions to the IITs are done through a national-level joint entrance examination. The joint entrance examination consists of two stages.The first stage of the joint entrance examination is known as JEE Main Exam.The second stage of the joint entrance examination is known as JEE Advance exam.",
     imp:"This is was introduced for the admission of students into various UG or Undergraduate Courses providing Architecture as well as Engineering courses.JEE Mains can land you into some of the best educational institutes like Indian Institute of Technology (IITs), Government Funded Technical Institutes (GFTIs), National Institute of Technology (NITs) and some other state affiliated colleges.The most important benefit you will get after clearing your JEE Mains exams would be that you will be further eligible for hiving the JEE Advanced Examination. If you score really good in both the examination that is JEE Mains and JEE Advanced, you will have more options to get into the best as well as the top notch engineering colleges. Also JEE Mains is the door to not only top private institutions but also to the best of the best government colleges. So, that is also a benefit for you.JEE Mains also provides the candidates with the opportunity to improve their scores again in the examination. That is why the JEE Mains examinations are conducted in multiple sessions every year. This will also help in saving your year as you have multiple chances to score the best."
    },
    {
        id: 26,
        title: "NEET",
        course:"Akash-Institute,Ellen,Career-Launcher,Unacademy,Byju's",
      what:"National Eligibility and Entrance Test or NEET is the one examination which would be considered for filling about 54,000 medical seats across the country. As per the Supreme Court’s order in 2016, NEET would be the only examination to fill the All India Quota Seats as well as the State Level Quota seats across the country. The examination is also valid for filling the private college seats across the country.",
     img:"https://www.india.com/wp-content/uploads/2022/05/neet.jpg",
     vid:"https://www.youtube.com/watch?v=RlbBUfvoNTE",
     ben:"The National Eligibility cum Entrance Examination is the only medical entrance examination in India to fill all the medical seats in India which includes the admissions to AIIMS and JIPMER, and also to the admissions of medical courses abroad. To be qualified for the NEET examination, a student must be at least 17 years of age. Besides, the students must also score a total of at least 50% marks in Physics, Chemistry, and Biology.More time to attempt the exam.Students who will appear for the NEET exam will have to attempt only 180 questions for 3 hours as compared to the previous years. This gives the students more time to think and concentrate on their papers and a chance to score more in the exam.Saves time and money: The introduction of the NEET exam changes a lot in the medical entrance examination. It saves the students’ time from appearing multiple exams for the admissions to the medical colleges. Having one exam to attempt saves the student’s money as well since there will only be one-time registration.Uniform Admission:NEET exam is introduced to bring about the uniform admission process to the medical colleges in India. The admissions to the medical universities are only accepted through NEET qualification. It also proves the transparency in the medical admission process where the admissions to the Private/Government/Deemed medical colleges in India are held fairly to the deserved medical aspirants. ",
     type:"NEET exam is conducted by NTA. The question paper for the exam covers topics from Physics, Chemistry, and Biology. Furthermore, Biology is divided into two sections which include Botany and Zoology.The number of questions set for the NEET exam will be 180 questions which carry four marks each. In case of the wrong answer, one mark will be deducted. If the candidate does not attempt any question, no marks will be allotted/deducted. Candidates have a maximum of three hours to answer every question.",
     imp:"With NEET being the only medical entrance examination in India, it prevents the private medical colleges from conducting any entrance examination of its own. NEET also prevents private universities from admitting students who do not qualify to pursue Medical.Students who qualify NEET will get the opportunity to secure a seat at any Medical colleges in any State.   Qualifying NEET with high scores and secure a good rank in the All India Merit List enables the students to get a seat into the most prestigious medical college in the country.The NEET entrance exam helps the medical aspirants to pursue medical courses or MBBS from Abroad.NEET exam reduces the unnecessary stress for the medical aspirants as they only have to appear for one exam to get the admission to any medical college.These are some of the reasons why the NEET exam is important for admissions to medical colleges in India and also abroad. Some of the medical universities abroad offer MBBS seats to the medical aspirants after they qualify the NEET exam."
     
      },
    {
        id: 27,
        title: "CAT ",
        course:"Physic Wallah,Unacademy,2IIM,Career-Launcher,Bodheeprep",
      what:"The Common Admission Test (CAT)[2] is a computer based test for admission in graduate management programs. The test consists of three sections: Verbal Ability and Reading Comprehension, Data Interpretation and Logical Reasoning and Quantitative Ability. The exam is taken online over a period of three hours, with one hour per section. In 2020, due to the COVID precautions, The Indian Institutes of Management Indore decided to conduct the CAT Exam in 2 hours with 40 minutes devoted to each section.[3] The Indian Institutes of Management started this exam and use the test for selecting students for their business administration programs (MBA or PGDM). The test is conducted every year by one of the Indian Institutes of Managements based on a policy of rotation.",
     img:"https://coursesxpert.com/wp-content/uploads/2021/05/CAT-Exam-India.jpg",
     vid:"https://www.youtube.com/watch?v=hSHQKnwpotw",
     ben:"Academic Prestige :The most significant advantage of taking the CAT exam is the opportunity to study in the best management colleges in India. These colleges include all the IIMs, FMS Delhi, MDI Gurgaon, XLRI Jamshedpur, S.P. Jain Mumbai, etc. These are the pioneer institutes in the field of management and entrepreneurial education. All the institutes help you to build the essential corporate skills which will enhance your professional career growth. Whether you get into IIMs or any other similar management institution, the recognition of these colleges is renowned extensively.Time Management.Time is undoubtedly a crucial part of anyone’s life. If you are an excellent timekeeper, then you will perform well in every aspect of life. With less time at hand and more questions to solve, CAT helps you develop the greatest asset, Time. From the first day of preparation to the first day of selection, all the stages of the CAT exam require hard work and effort with time management skills to ensure success. If you are good with your needles, then believe us, half of your job is done already, and CAT makes it more rigid. Recognition:When you clear an exam like CAT, you will be considered a valuable and knowledgeable individual. The respect and prestige you get are unparalleled, and the backing of such a prestigious degree from a tier-1 college makes you eligible for high salary packages. If you compare an IIM degree with any regular MBA institute, you will see the prestige associated with the name. You will get selected for an interview easily, and you get better salaries; the promotions are usually higher with aided responsibilities for a top B-School graduate. Your chances of selection in any of the renowned organizations become easy. Due to the international recognition associated with these institutions, various MNCs will not hesitate to hire you.Personality Development :Participating in or qualifying for any such exam like CAT will not only fetch you a good job and salary but also develop you as an individual. After preparing for the CAT examination for six or more months, you build critical and analytical thinking towards everything. Your perspective thought process, and awareness of your surroundings will change drastically. Your common sense will improve, and you will make sound decisions. The most important quality you produce is patience. Yes, you will learn to be patient, which is not a rocket science thing. Having patience under every circumstance will make you a better individual for society as well as for the organization.    ",
     type:"The CAT administering IIM will soon release the latest CAT 2023 exam pattern. The CAT exam pattern 2023 is likely to remain the same as was for CAT 2022. The exam pattern of CAT will help candidates understand the structure of the CAT question paper and marking scheme which will help in better CAT exam preparation.Before going to appear for the CAT 2023 exam, one should know what is the CAT exam pattern. The CAT paper pattern and the test procedure will be announced along with the CAT 2023 exam dates and the notification. Candidates planning to opt for CAT 2023 must familiarize themselves with the latest CAT exam paper pattern and syllabus 2023.",
     imp:"CAT is a computer-based management aptitude test conducted by the IIMs primarily to evaluate and shortlist candidates for postgraduate programmes. India’s premier national institutes, such as IIM, provide high-quality education in management and research. Therefore, the CAT exam benefits are immense. Besides, the exam is conducted annually.CAT is a computer-based management aptitude test conducted by the IIMs primarily to evaluate and shortlist candidates for postgraduate programmes. India’s premier national institutes, such as IIM, provide high-quality education in management and research. Therefore, the CAT exam benefits are immense. Besides, the exam is conducted annually. Rates of success in obtaining admissions to two-year post-graduate programmes, which are the flagships of IIMs, are based only on merit. CAT exams follow a rigorous selection process comprising personal interviews, written ability tests and discussions, and finally, scores in the exam.The candidate can appear for the exam as many times as they want; there is no limit to the attempts.Rates of success in obtaining admissions to two-year post-graduate programmes, which are the flagships of IIMs, are based only on merit. CAT exams follow a rigorous selection process comprising personal interviews, written ability tests and discussions, and finally, scores in the exam.The candidate can appear for the exam as many times as they want; there is no limit to the attempts."
      
      },
   
  ];
  
  export default eduList2;
  