const list2 = [
    
    {
      id:1,
      title: "Cheese-Veg-cutlet",
      detail: "Vegetable Cutlet also called as veg cutlet are crisp, savory, tender patties made with a mix of hearty veggies, savory spices, fresh herbs and crispy breadcrumbs. Cutlet recipe is a popular snack in Indian cuisine and there are so many ways to make them. These vegan vegetable cutlet are pan fried to keep them healthy, but as you prefer you can deep fry or shallow fry.Veggie cutlets are crumb coated or breaded so that they become crispy. To crumb coat a batter is made of all-purpose flour (maida). For a healthier option instead of all-purpose flour, opt to use gram flour (besan) or maize flour (cornmeal or makki ka atta). You can skip breading the veg cutlet if you want. ",
      time: "35 mins",
      img:"https://www.chefkunalkapur.com/wp-content/uploads/2021/06/veg-cutlet-1300x866.jpg?v=1622699666",
      vid:"https://youtu.be/L1VeIztoAFc",
      ing:" oil– 4tbsp Asafoetida (Heeng) – ½ tsp Cumin – 1½ tsp Green chilli chopped – 1tsp Ginger chopped – 2tsp Beans chopped – ½ cup Carrots chopped – ½ cup Cauliflower chopped – ½ cup Chilli powder – 1tsp Coriander powder – 1tbsp Turmeric – ½ tsp Salt – to taste Potato boiled & mashed – 1½ cup Garam masala – ½ tsp Kasoori methi pwd – ½ tsp Chaat masala – 1tsp Bread crumbs – ¾ cup Cheese cubes – few For Slurry: All purpose flour (Maida) – 1 cup Salt – 1 pinch  Water – ½  cup (approx) Bread crumbs – for coating Oil – to fry" ,
      steps: "To make the veg cutlet heat a pan and pour in oil. Add heeng, cumin green chilli and ginger. Cook on high heat for a minute. Add beans, carrots, cauliflower and cook on high heat for 3-4mins. Add chilli powder, coriander, turmeric and salt. Cook for another minute Remove from heat on to a platter and let it cool complete. Once cooled mix in mashed potatoes, garam masala, chaat masla and bread crumbs. Mix them and divide into small balls. Fill of them with a cheese cube and roll it. Lightly flatten it to shape it into a tikki or a cutlet.For the batter mix together flour, salt and water to make a thick slurry. Heat oil in a deep pan and spread out the some bread crumbs separately on to a plate. Dunk the cutlet in the batter, let the excess flow off and then deep fry them on medium hot oil to get a crispy outside. Remove and serve with tomato ketchup."
    },
    {
        id: 2,
        title: "Veg Momos",
        detail: "A treditional north-east dish we made it in very easy way.momos recipe is very common in my house and i keep preparing it with a wide variety of stuffings. as a matter of fact, i end up making these cute looking dumpling with any leftover dry sabzi’s. in addition, to make my life easier i do get a square-shaped momos sheet here in asian supermarkets under the fridge section. so basically my job is to stuff the veggies and shape it as required and steam it till it gets cooked. but in this recipe, i have showcased both stuffing and momos sheet from scratch. momos sheet can be overwhelming for a novice chef and hence you can opt for frozen momos sheets. but the stuffing is extremely simple and can be made in minutes.",
        time:"20min",
        img:"https://www.chefkunalkapur.com/wp-content/uploads/2021/05/Veg-Momos-2-scaled-e1620712323714-1300x809.jpg?v=1620705172",
        vid: "https://youtu.be/gWJePLW3ygc",
        ing: "Ingredients of Vegetable MomosFor dough:2 cups Maida1/2 tsp Salt1/2 tsp Baking powderFor filling:1 cup Carrot, grated1 cup Cabbage, grated1 tbsp Oil1/2 cup Onion, finely chopped1 tsp Garlic, chopped1 tsp Soya sauceto taste Salt1/4 tsp Vinegar1/4 tsp Black pepper",
       steps:"Mix the maida, salt and baking powder and knead to a stiff dough with water.2.Heat oil and add the onion and garlic. Saute over high heat and add the carrot and cabbage. Turn around over high heat till glossy.3.Take it off the heat and mix in the soya sauce, salt, vinegar and black pepper.4.Roll the dough thin (translucent) and cut into four-five rounds.5.Take a round, wet edges and place some filling in the center.6.Bring edges together to cover the filling. Twist to seal and fill the rest in the same way.7.Steam for about 10 minutes and serve with soya sauce and chilli sauce."
    },
    {
        id: 3,
        title: "Baked-Samosa",
        detail: "Say bye to traditional calories filled samosa and prepare regular samosa with a healthy twist. momos recipe is very common in my house and i keep preparing it with a wide variety of stuffings. as a matter of fact, i end up making these cute looking dumpling with any leftover dry sabzi’s. in addition, to make my life easier i do get a square-shaped momos sheet here in asian supermarkets under the fridge section. so basically my job is to stuff the veggies and shape it as required and steam it till it gets cooked. but in this recipe, i have showcased both stuffing and momos sheet from scratch. momos sheet can be overwhelming for a novice chef and hence you can opt for frozen momos sheets. but the stuffing is extremely simple and can be made in minutes.",
      
        time:"30min",
        img:"https://i.ytimg.com/vi/IvaqUQFqfoU/maxresdefault.jpg",
        vid:"https://www.youtube.com/watch?v=IvaqUQFqfoU",
        ing:"For Dough:All-purpose flour/Maida: To make baked samosa dough I have used regular APF or maida.Salt to taste Oil: Use any vegetable oil or ghee as per your preference. Ajwain/carom seeds (optional):For Stuffing:Potato - 2 (boiled) (medium size) Peas - 1/2 cup Oil - 1 to 2 tsp Red chilly powder - less than 1/4 tsp Salt - 1/4 tsp (as per taste) Green chilly - 1 to 2 (finely chopped) Ginger - 1/2 inch piece (grated) Green coriander - 1 to 2 tbsp (finely chopped) Mango powder - 1/4 tsp Coriander powder - 1/2 tsp Cumin powder - 1/2 tsp Garam masala - less than 1/4 tsp", 
        steps: "For baked samosas, take flour in any vessel for kneading the dough. Add salt, sugar, dry active yeast and oil in the flour and mix well. With help of lukewarm water, knead soft dough. Keep kneading the dough for 4 to 5 minutes until smooth (to knead this much quantity of flour, approx 1/3 cup of water is used). Grease the dough with some oil. Cover the dough and keep it aside for 2 hours. Dough puffs double from its original size. When the dough is fermented, we can use it for making samosas. Prepare the Stuffing:Take some oil in a pan and heat it sufficiently. When oil is hot, add green chilly, ginger, cumin powder, coriander powder and peas. Saute the peas for 2 minutes. Peel the potatoes and mash them finely. Add salt, red chilly powder, garam masala, mango powder and green coriander. Mix all ingredients really well. Turn off the flame and take out stuffing in a bowl, so that it cools quickly. Knead the dough again. Make four lumps from the dough and roll giving them a round shape. Take one dough ball, dust with some dry flour and roll out thinly like chapatti with 7 to 8 inch diameter. Divide the rolled poori in two equal halves.Take one part and place it over your hand. Spread some water on the side from where its cut and then lift from the other side and stick it nicely, giving it a cone shape. Place 1 to 1.5 tsp stuffing inside the cone. Spread some water on the corners , give a fold at the back side and stick both the sides to close the stuffing. Place this samosa in erect position (upper corner on the top) on the tray. Likewise fry all the samosas and place them at some distance on the tray. Cover and keep aside the tray for half an hour in such a way that their shape remains intact. After half an hour, bake the samosas in oven. Preheat the oven at 180 degree centigrade. Place the tray in oven and bake samosas on 180 degrees for 10 minutes first. Check the samosas, they have turned slightly brown. Bake the samosas for 5 more minutes. Within 15 minutes, samosas turn golden brown in color. Samosas are now ready. Piping hot baked samosas are ready. Serve with tomato sauce, green coriander chutney and relish eating. Suggestion:You can make stuffing as per your taste. You can make peas-paneer stuffing or use some dry fruits along with paneer-peas for making the stuffing. "
    },
    {
        id: 4,
      title: "Manchurian",
      detail: "There are all fans of momos, they are of many types and we like them in every way.  Today we are going to the recipes taste good and are shared with step by step photos. You can make either of them as per your choice. Example: you can make veg manchurian dry as a starter snack or veg manchurian gravy for a Chinese main course.",
      
      time:"35min",
      img:"https://firebasestorage.googleapis.com/v0/b/cscom-2019.appspot.com/o/content%2F2014%2F01%2Fvmir_640x360.jpg?alt=media",
        vid:"https://youtu.be/MwqiyCl4DaM",
        ing:"Carrot, Cauliflower, Cabbage, French Beans - 1/2 cup each (finely chopped) Onion - 1/2 cup Plain Flour - 4 - 5 tbsp  Corn Flour - 4 - 5 tbsp Salt - as per taste Black Pepper - as per taste Green Chili - 1 tsp Garlic - 1 tsp Oil - to fry For the sauce onions - 1/2 cup Spring Onions Greens - 3 - 4 tbsp Chili Vinegar - 1 1/2 tsp Salt - to taste Black Pepper - to taste Garlic - 1 tsp Green Chili - 1 tsp Soya Sauce - 1 tbsp Green Chili Sauce - 1 1/2 tbsp Red Chili Sauce - 1 1/2 tbsp Schezwan Sauce - 1 1/2 tbsp Oil -"
       
        
        ,
        steps: "For Mix Veg Balls: Heat the oil for frying the veggie balls. In a bowl, mix all the rest ingredients very well and quickly make the balls out of it. Now fry them at med flame until half done/crust forms. Take the veg balls out of the oil and heat the oil to high. Now put in the balls again and fry till brown. Transfer to a tissue paper.Enjoy them as it is, they are delicious.. Or make a sauce, and enjoy as a manchurian.For completing manchurian: Heat a pan/wok with 2 tbsp oil in high flame. Throw in the garlic and chili. Saute for a couple of secs..Add in the onions, spring onion whites. Stir well and cook for a few secs.. Add in a handful of spring onion greens, salt and pepper to taste, soy sauce, chili sauce, red chili sauce, schezwan sauce, ketchup, vinegar and about 2 tbsp of water. Now throw in the veggie balls and stir well. Garnish with spring onion greens and enjoy!"
    },
    
    {
        id: 5,
      title: "Chhole Bhature",
      detail: "Chole Bhatoore is Punjab's favourite dish. It is very spicy and delicious in taste.Chole Bhature also known as Chana Bhatura is one of the most popular Punjabi dish liked almost all over India. Chole stands for a spiced tangy chickpea curry and Bhatura is a soft and fluffy fried leavened bread. Chola Bhatura always make for a delicious and filling meal. In this recipe post, I have included the step-by-step pictorial of making both the chana curry as well as a quick bhatura that is made without yeast.",
      
     
      time:"45min",
      img:"https://storage.googleapis.com/cscom-2019.appspot.com/uploads/2018/09/Bhature_640x360.jpg?alt=media",
      vid:"https://www.youtube.com/watch?v=FU1ZVLMbWjA",
      ing:"2 Cups chick peasTea LeafDried Amla2 tsp oil1 Bay Leaf1 Cinnamon stick2 Green cardamom1 tsp cumin seeds1 Black cardamom8 Black peppercorns3 Cloves2 onions, chopped1 tsp garlic1 tsp ginger1 tsp turmeric powder1 tsp red chilli powder1 tsp coriander powder1 tsp cumin powder3 tsp salt1 cup water1 tomato, chopped1 bunch coriander leaves1 tsp yeast2 tsp sugar1 cup water2 cup maida1/2 cup wheat Flour",
      steps: "Take a bowl and boil chickpeas along with tea leaf and dried amla.Masaaledaar Chole Bhature2.Now take a pan and pour oil in it.Masaaledaar Chole Bhature3.Put bay leaf, cinnamon stick, green cardamom, cumin seeds, black cardamom, black peppercorns and cloves in the oiled pan. Saute them togetherMasaaledaar Chole Bhature4.Now add the chopped onions into it and saute till golden brown.Masaaledaar Chole Bhature5.Add garlic, ginger, turmeric powder, red chilli powder, coriander powder, cumin powder and salt. Mix well.Masaaledaar Chole Bhature6.Now add water to the mixture followed by the boiled chickpeas and chopped tomato.Masaaledaar Chole Bhature7.Mix them well and transfer the mix into a pressure cooker.Masaaledaar Chole Bhature8.Add coriander leaves and pressure cook it.Masaaledaar Chole BhatureTo prepare Bhature:1.Take yeast in a bowl, add sugar and water to it.Masaaledaar Chole Bhature2.Stir them together.Masaaledaar Chole Bhature3.Take maida in a big bowl, add wheat flour, salt and the yeast mix to it.Masaedaar Chole Bhature4.Stir a little and add water to it.5.Knead the mixture to form a dough.Masaaledaar Chole Bhature6.Cover the dough with a cloth and leave it for 2-3 hours for the yeast to work.Masaaledaar Chole Bhature7.Now, take the dough and roll into round balls like chapatti.Masaaledaar Chole Bhature8.Put them for frying in a hot oil pan.Masaaledaar Chole Bhature9.Serve them hot along with Chole."
    },
    {
        id: 6,
        title: "Rajma Paratha",
        detail: "Deffinetly you eat many types of Parathas here we made very tasty and healthy rajma paratha recipes.Chole Bhature also known as Chana Bhatura is one of the most popular Punjabi dish liked almost all over India. Chole stands for a spiced tangy chickpea curry and Bhatura is a soft and fluffy fried leavened bread. Chola Bhatura always make for a delicious and filling meal. In this recipe post, I have included the step-by-step pictorial of making both the chana curry as well as a quick bhatura that is made without yeast.",
      
      time:"30min",
        img:"https://i0.wp.com/sandhyahariharan.co.uk/wp-content/uploads/2018/04/rajma-paratha-4-of-5-min.jpg?resize=768%2C1152&ssl=1",
        vid:"https://www.youtube.com/watch?v=zzhb2r4TAjM",
        ing:"For Chapathi Dough:2 Cups Whole Wheat Flour1 Cup of Water + few tsp Approx 55%Salt ¾ -1 Tsp1 Tsp Oil It can be sunflower, vegetable or even sesame oilFor Paratha Filling:1 Tsp Sunflower Oil 11/2 Cup Cooked Kidney Beans/ Rajma 1 Tbsp freshly grated Ginger 1 medium sized onion finely chopped 1/2- 1 Tsp Chilli Powder add more of you like it spicer 1/2 Tsp Cumin Powder 3/4 Tsp Garam Masala Tsp Coriander leaves Oil/Ghee as needed for making Paratha's1 Tsp Lemon Juice",
        steps:"Add whole wheat flour, salt to a mixing bowl. Add water in a steady stream and knead them until well combined. Add the oil and knead them again until the dough is soft, supple and not sticky. Cover and set it aside for atleast 20 minutes before you make the paratha.In a food processor, add cooked kidney beans,coriander leaves, ginger, onions, cumin powder, chilli powder, garam masala, salt and whizz until the kidney beans is mashed and the rest of the ingredients are well combined. Heat oil in a pan, add the kidney beans mixture, lemon juice and cook for a few minutes until any water left is evaporated.Second Method:Mash the Kidney beans and set aside. Finely chop the the onions, coriander leaves and set aside.Heat Oil in a pan, add onion, ginger paste and saute for 2 minutes. Add the mashed kidney beans, spice powders,lemon juice, salt to the pan and cook until well combined.Divide the dough into 10 equal portions. Pick one portion of dough at a time, dust some flour and spread them with the roller into thin disk of 5cm or so. Spread 1/2 a tsp of oil in the middle of the rolled dough, place the kidney beans/ rajma paratha mixture right in the middle leaving space in the edges to seal.Starting right from the edge, begin pleating and seal the filling mixture with the dough. Dust some flour and roll the dough gently, ensuring the filling doesn't come out.Heat a non-stick pan / tava to a high temperature. Place the rolled Rajma paratha on the tava and cook for a 1-1.5 minutes or so. When the base is cooked, flip the paratha and cook again.Spread a teaspoon of oil on part cooked paratha. Flip again and you will find the paratha cooked nicely with a couple of charred/black spots. Spread some more oil and you will find the paratha puffs up really well.You may even use spatula's to press the edges of the dough, just to ensure they cook well.Remove the cooked paratha's from the flame into a casserole and keep them covered.Serve warm Rajma Paratha with lots of yogurt."
    },
    {
        id: 7,
        title: "Methi Malai Matar ",
        detail: "As the cold starts to set in Methi also begins to be available in the market. methi malai matar with detailed photo and video recipe. a mild and creamy north indian curry recipe made with fenugreek leaves, peas and cream. it is known for its combination of mildly sweet, spicy and mild bitterness taste in each serving. it is ideally served with choice of indian flat bread like roti, chapati but can also be served with a combination of garlic naan and jeera rice.",
    
      time:"20min",
        img:"https://pipingpotcurry.com/wp-content/uploads/2019/08/Methi-Matar-Malai-12.webp",
        
        vid:"https://www.youtube.com/watch?v=ZxP5uNHkW0s",
        ing:"3 Cups Methi Leaves (Fenugreek Leaves) , chopped1 cup Green peas (Matar)3 Onions ,cut in four pieces each2 Green Chillies10 Cashew Nuts4 Cloves Garlic1 Inch Ginger1/2 cup Milk1/2 tbsp Coriander Powder (Dhania)1/2 cup Fresh cream1/4 tbsp Cardamom Powder (Elaichi)1/2 tbsp Sugar1 tbsp Kasuri Methi (Dried Fenugreek Leaves)to taste Salt3 tbsp Ghee/OilFor Dry Masala2 Green Cardamom3 Cloves (Laung)1 tbsp Cumin seeds (Jeera)5 Whole Black Peppercorns1/2 Inch Cinnamon Stick (Dalchini)1/2 Mace (Javitri)1 Black cardamom (Badi Elaichi)",
        steps:"First make the dry masala. Add green cardamom, cloves, cumin seeds, whole black peppercorns, cinnamon stick, mace and black cardamom in a blender and make ground spice powder and keep it aside.2.Next, add some water in a heavy bottomed pan and let it boil. Once it starts boiling add onion, cashew nuts, green chillies, garlic and ginger to the boiling water.3.Once it is boiled, drain the water and make a ground paste of boiled onion, cashew nuts, green chillies, ginger and garlic cloves and keep it aside.4.Next, blanch the fenugreek leaves to enhance the colour of the dish. Add methi leaves in hot water in a pan. After a minute, add it to the chilled water for about 2 minutes.5.Now drain the water and squeeze out whatever remaining water in methi and keep it aside.6.Heat ghee in a wok or a heavy bottomed pan, add wet ground paste and cook it for 5 minutes till spice starts releasing oil.7.Now add green peas and milk, let it cook for another minute.8.Add dry spice powder which we made earlier and coriander powder. Mix it well and cook for another 3 to 4 minutes on medium flame.9.Now add blanched methi, salt, sugar, mix it well and cook for 2 more minutes.10.If you find consistency too thick, you can adjust it by adding milk.11.Add cardamom powder, kasuri methi and cream, mix well and cook for 2 to 3 minutes more.12.The methi malai mattar is ready! Serve hot."
    },
    {
        id: 8,
        title: "Tandoori chicken",
        detail: "Tandoori Chicken is a dish which is most loved in The Nothern and many parts of Delhi and Punjab. The chicken tikka, along with tandoori chicken, are dishes that have made Indian chicken popular all over the world. Boneless chicken pieces are marinated in yoghurt and spices and then grilled over a tandoor. In my version of this famous recipe, the mustard oil and the green chillies add a pungency that is unmatched. In the absence of a tandoor, these can be grilled in the Oven at a high temperature or over a grill as well. Most important to remember is to baste it with butter or oil to ensure it stays juicy inside and crisp outside.",
        time:"30min",
        img:"https://www.cubesnjuliennes.com/wp-content/uploads/2022/12/Tandoori-Chicken-Recipe.jpg",
        vid:"https://www.youtube.com/watch?v=SE0y69w9cWE",
        ing:"3 tablespoons vegetable oil,1 teaspoon ground coriander, 1 teaspoon ground cumin,1 teaspoon ground turmeric,1 teaspoon cayenne,1 tablespoon garam masala,1 tablespoon sweet (not hot) paprika,1 cup plain yogurt (can sub buttermilk),2 tablespoons lemon juice, 4 garlic cloves, minced, 2 tablespoons minced fresh ginger,1 teaspoon salt, 4 whole chicken leg quarters (drumsticks and thighs), skinless, bone-in",
        steps:"Heat the spices in oil:Heat the oil in a small pan over medium heat, then cook the coriander, cumin, turmeric, cayenne, garam masala and paprika, stirring often, until fragrant (approximately 2-3 minutes). Let cool completely.Bloom Spices in Pot for Tandoori Chicken Marinade:Whisk spices into yogurt, add lemon juice, garlic, salt, ginger:Whisk the cooled spice-oil mixture into the yogurt, then mix in the lemon juice, garlic, salt and ginger.Mix Spices in Bowl with Yogurt for Grilled Tandoori Chicken,Cut deep slashes into chicken, coat with marinade, chill:Cut deep slashes (to the bone) in 3-4 places on the leg/thigh pieces. Just make 2-3 cuts if you are using separate drumsticks and thighs. Coat the chicken in the marinade, cover and chill for at least an hour (preferably 6 hours), no more than 8 hours.Prepare grill:Prepare your grill so that one side is quite hot over direct heat, the other side cooler, not over direct heat. If using charcoal, leave one side of the grill without coals, so you have a hot sideand a cooler side. If you are using a gas grill, just turn on one-half of the burners.Use tongs to wipe the grill grates with a paper towel soaked in vegetable oil.Shake off excess marinade, place chicken on hot side of grill:Take the chicken out of the marinade and shake off the excess. You want the chicken coated, but not gloppy.Put the chicken pieces on the hot side of the grill and cover. Cook 2-3 minutes before checking.Turn the chicken so it is brown (even a little bit charred) on all sides.Cover and cook for at least 20 minutes, up to 40 minutes (or longer) depending on the size of the chicken and the temperature of the grill. The chicken is done when its juices run clear.Let it rest for at least 5 minutes before serving. It’s also great at room temperature or even cold the next day.Serve with a an,and Indin flatbread, or with Indian style rice, with yogurt-based raita on the side."
    },
    
    {
        id: 9,
        title: "Cheese-Cake ",
        detail: "If you are thinking of trying to make a different cake then try this Chena Cake, you will surely like it.This creamy, soft and egg-free New York Style Cheesecake recipe is a favorite among my friends and family. When served with my simple chocolate sauce, this elegant dessert is both beautiful and delicious!",
      
      time:"20min",
        img:"https://www.chefkunalkapur.com/wp-content/uploads/2021/05/cheese-cake-2-scaled-e1635216358218-1300x881.jpg?v=1620792048",
        vid: "https://youtu.be/24cOXPkxtXY",
        ing:"For the base:Digestive Biscuits – 160 gms Melted butter – 80gms/ ⅓ cup or the Filling:Hung Curd (thick) – 1\½ cup Condensed milk – 1cup Cream (unsweetened) – ½ cup Vanilla extract – 1 tsp For slurry:Warm milk – 6tbsp Cornstarch 15gms/2tbsp For Strawberry Sauce:Strawberries (halved) – 1cupSugar – ¼ cup Water – a dash. Accompaniments:Whipped cream Mint sprigs ",
        steps:"To make the cookie crumb base crush the biscuits with hands then add them to the grinder. Once they turn into a fine crumb add in melted butter and mix them. Spread it on to a silicon mould (8inch dia and 2inch in height). Press down the crumbs using the flat base of a cup to tightly pack it. Refrigerate for at least 30mins before use.For the filling mix together hung curd, condensed milk, cream and vanilla extract. Separately mix together warm milk with cornstarch and add to the filling. Mix well so there are no lumps. Pour this mixture on to the cookie crumb.Place the silicon mould on to a microwave safe plate and place it inside the microwave. Choose the option microwave, take the intensity to 800-900watts and cook for 10mins. Alternatively if your microwave has powder option from low to high then choose medium power and cook for 10mins.Remove from the oven and allow it to cool completely. Place it in the fridge for at least 2 hours (overnight is preferred) and then remove the cake from the mould.To make he strawberry sauce place the strawberries along with sugar an sa dash of water in a pan and cover and cook for approx 8 mins. Remove from heat and let it cool.Cut slices from the cheesecake and pipe some whipped cream on top. Pour the strawberry sauce on top and garnish with mint sprigs. Serve chilled. NOTE:Recipe needs silicon mould that can go in a microwave Microwave it at 800w for 10mins"
    },
    {
        id: 10,
      title: "RasMalai",
      detail: "Rasmalai is the most preferable sweet out of all the other Bengali sweets. If you wish to make This Bengali specialty is made with rasgulla (sweetened balls of paneer) soaked in sweetened, thickened milk that has been scented with cardamom and saffron. The result is a creamy, dreamy dessert that absolutely melts in your mouth. Make this soft and tasty rasmalai recipe with my easy step-by-step photos.",
     
      time:"40min",
      img:"https://www.chefkunalkapur.com/wp-content/uploads/2021/06/Rasmalai-3-1300x867.jpg?v=1625130326",
        vid:"https://www.youtube.com/watch?v=LECpZPkP9Wk",
        ing:" Milk- 1.5 litre Sugar- Half cup Cardamom powder- One pinchDry fruits- 1 teaspoonCorn flour- 1 teaspoon Saffron-infused milk- 1 tablespoon Vinegar- 1 teaspoon",
        steps:"Let the milk boil.Add some cold water and let it cool.Add vinegar to curdle.Strain the whey water out and keep the chhena.Add cornflour and mix well.Make small roundels and keep aside.Add sugar and water in a pan and boil.Add the chhena roundels to the sugar-water and cook for 10 minutes.Heat some more milk and add saffron-infused milk, cardamom powder, dry fruits and mix.Add sugar and boil till it reduces to half.Place the cooked chhena roundels in the milk and let it cool for 4 to 5 hours.And a bowl of tempting rasmalai is ready to be served. Enjoy!"
    },
    {
        id: 11,
        title: "Gujiya",
        detail: "Gujiya recipe to make our Holi Festival or party merrier and sweet.Learn to make the popular Gujiya recipe that is a classic North Indian sweet of crisp, flaky pastry filled with khoya (milk solids) and nuts stuffing. Gujia is generally fried but in this recipe post, I am sharing both the fried and baked versions. Take your pick and enjoy making these traditional sweet for Holi or Diwali festival. ",
      time:"40min",
        img:"https://www.chefkunalkapur.com/wp-content/uploads/2021/03/Gujjia.jpg?v=1617940633",
        vid: "https://youtu.be/kCMNxYEq7rU",
        ing:"For the dough:2 cups refined flour1 cup clarified butterWater (to mix)For the filling:1 cup khoya1 cup sugar1 tsp green cardamom, powdered1 tbsp almonds, finely choppedGhee (for deep-frying)For the syrup:1 cup sugar1 cup water",
        steps:"Prepare the dough:1.Rub 1/4 cup ghee into the flour and knead into a stiff dough with water.2.Leave to rest for at least half an hour.Prepare the filling:1.Saute the khoya over medium heat till it looks slightly fried.2.Take off the heat and when it cools, mix in the sugar, cardamom and almonds.3.Shape the filling into ovals about 21 cm length and 1 cm thickness.4.Make balls of the dough and roll out into 1 cm / 1/8 in thick rounds.5.Take a round, wet the edges with water and place a piece of filling over one half.6.Fold the other half over and press the edges together to seal.7.Either cut off the edge with a fancy cutter or make a design by pinching and twisting all along the sealed edges.8.Make all the gujiyas in this way. Heat ghee in a kadahi. To check if the ghee is hot enough put a piece of dough in it. If it comes up at once, add as many gujiyas as fit in comfortably.9.Turn them over and lower the heat to medium. Fry till golden brown on all sides. Lift out and leave to drain on absorbent paper.10.Makesugar syrup by cooking water and sugar together, till one thread consistency11.Dip the gujiyas in it, lift and let dry on a plate.12.Fry the rest, increasing the heat for a few seconds before adding the next lot.13.Can be eaten hot or at room temperature and can be stored in air-tight containers."
    },
    {
        id: 12,
        title: "KalaKand",
        detail: "For making kalakand instantly, Kalakand is an Indian sweet fudge made with milk and often flavored with cardamom. Plain kalakand is the most popular one but there are several other variations to it like mango kalakand, rose kalakand etc. This is an easy to make sweet for festivals like Diwali, Raksha Bandhan and more! ",
     
        time:"35min",
        img:"https://www.chefkunalkapur.com/wp-content/uploads/2021/03/Kalakand-1-1300x867.jpg?v=1621582979",
        vid:"https://youtu.be/EIRyiLQKSSw",
        ing:"(full cream) – 2 lt Milk100gms Sugar 2tsp Vinegar½ tsp Cardamom powder Pista Chopped – a handful",
        steps:"Boil milk and sugar and once it gets to a good boil add vinegar and keep cooking till it reduces. If the dana is too big then you can mash it with the back of the spoon. Once it is thick and starts to leaves the sides of the kadai remove it to a tray and let it set. Once cool cut and serve. Kalakand can be garnished with chopped pistachios and almonds.Make sure there is no excess water/milk left in the kadai, this is an indication that Kalakand is ready."
    }
  ];
  
  export default list2;
  